[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [
  { access = "read-write", path = "./deployments" },
  { access = "read", path = "./script" },
]

[etherscan]
sepolia = { key = "${API_KEY_ETHERSCAN}" }

[rpc_endpoints]
local = "http://localhost:8545"
sepolia = "https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_KEY}"
optsepolia = "https://opt-sepolia.g.alchemy.com/v2/${ALCHEMY_KEY}"
base = "https://base-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
